version: "2.2"

services:
  logstash:
   image: docker.elastic.co/logstash/logstash:8.12.2
   labels:
     co.elastic.logs/module: logstash
   user: root
   ports:
     - 5044:5044
     - 9600:9600
   volumes:
     - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
     - "./pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro"
   environment:
     - xpack.monitoring.enabled=false
     - ELASTIC_USER=elastic
     - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
     - ELASTIC_HOSTS=https://ecp-elasticsearch:9200
